services:
  postgres:
    image: postgres:latest
    container_name: superset_postgres
    environment:
      POSTGRES_USER: superset
      POSTGRES_PASSWORD: superset
      POSTGRES_DB: superset_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - road-safety-network

  superset:
    image: apache/superset:latest
    container_name: superset_app_new
    environment:
      SUPERSET_SECRET_KEY: 'thisISaSECRET_1234'
      SQLALCHEMY_DATABASE_URI: "postgresql+psycopg2://superset:superset@superset_postgres:5432/superset_db"
    volumes:
      - superset_home:/app/superset_home
      - ./superset_db/superset.db:/app/superset_home/superset.db
    # - ./superset_export:/app/superset_export
    # - ./init_superset.py:/app/init_superset.py  # Línea agregada
    depends_on:
      - postgres
    ports:
      - "8088:8088"
    networks:
      - road-safety-network
    command:
      - /bin/bash
      - -c
      - |
        pip install gevent && \
        superset db upgrade && \
        superset init && \
        gunicorn -w 2 -k gevent --timeout 60 -b 0.0.0.0:8088 "superset.app:create_app()"
        python /app/init_superset.py

  carga-db:
    image: python:3.12
    volumes:
      - ./db manage/carga-db.py:/app/carga-db.py
      - ./db manage/crear-tablas.sql:/app/crear-tablas.sql
      - ./datos procesados:/app/datos_procesados
    depends_on:
      - superset
    networks:
      - road-safety-network
    command: >
      /bin/bash -c "pip install pandas psycopg2-binary sqlalchemy &&
                    python /app/carga-db.py"

networks:
  road-safety-network:

volumes:
  postgres_data:
  superset_home: